Repository noluyorAbi/C-Project, pull requests merged in 2024-12, with the labels that each got.

#24 Erweiterung der Konfigurationsparameter und Bugfix für Argumentenparser
  .clang-format
  README.md
  bin/sysprak-client
  client.conf
  main.c
  makefile
  modules/args_parser/args_parser.c
  modules/args_parser/args_parser.h
  modules/args_parser/config.c
  modules/args_parser/config.h
  modules/args_parser/constants.h
  tests/test_clientConf/test_clientConf.sh
  tests/test_performConnection/test_performConnection.c
Labels: bug, enhancement, chore, Review effort [1-5]: 3

#29 refactor receiveMessage: use loop to receive data until newline and adjust buffer handling
  modules/tcp_performConnection/performConnection.c
Labels: Review effort [1-5]: 3

#30 refactor: split workflows
  .github/workflows/build-project.yml
  .github/workflows/review-comment.yml
  .github/workflows/shared-memory-test.yml
  .github/workflows/valgrind.yml
  README.md
Labels: Review effort [1-5]: 3

#32 feat: renewed thinker and connector
  README.md
  main.c
  makefile
  modules/tcp_performConnection/client
  modules/tcp_performConnection/tcp_connection.c
Labels: Review effort [1-5]: 4
